const conjCategories = [
  { id: "basic",   label: "기초&연결",  short: "기초"    },
  { id: "cond",    label: "가정&조건",  short: "가정"    },
  { id: "will",    label: "의지&태도",  short: "의지/희망" },
  { id: "passive", label: "사역&수동",  short: "영향"    },
  { id: "aux",     label: "보조 동사",  short: "보조"    },
  { id: "adv",     label: "결합 변형",  short: "심화"    },
];

const conjTypes = [
  // ── 기초&연결 ──
    { id: "masu", label: "연용형", meaning: "~합니다", category: "basic", wrong: ["wish", "appear", "i"] },
    { id: "i", label: "연용형중지법", meaning: "~하기", category: "basic", wrong: ["masu", "imp", "neg"] },
    { id: "te", label: "て형", meaning: "~해서, ~하고", category: "basic", wrong: ["past", "prep", "try"] },
    { id: "neg", label: "부정형", meaning: "~하지 않다", category: "basic", wrong: ["neg_zu", "prohib", "pot_neg"] },
    { id: "past", label: "과거형", meaning: "~했다", category: "basic", wrong: ["te", "past_neg", "cond_tara"] },
    { id: "prog", label: "현재진행형", meaning: "~하고 있다", category: "basic", wrong: ["prog_past", "prog_neg", "try"] },

  // ── 가정&조건 ──
    { id: "cond_ba", label: "일반가정형", meaning: "~한다면", category: "cond", wrong: ["cond_neg", "cond_nara", "cond_tara"] },
    { id: "cond_tara", label: "완료가정형", meaning: "~하면, ~했더니", category: "cond", wrong: ["past", "cond_ba", "cond_to"] },
    { id: "cond_to", label: "필연가정형", meaning: "~하면 (반드시)", category: "cond", wrong: ["prohib", "cond_ba", "cond_tara"] },
    { id: "cond_nara", label: "전체가정형", meaning: "~한다면", category: "cond", wrong: ["cond_to", "cond_ba", "masu"] },

  // ── 의지&태도 ──
    { id: "imp", label: "명령형", meaning: "~해라", category: "will", wrong: ["vol", "prohib", "i"] },
    { id: "vol", label: "권유형", meaning: "~하자", category: "will", wrong: ["imp", "wish", "appear"] },
    { id: "prohib", label: "금지형", meaning: "~하지 마라", category: "will", wrong: ["cond_to", "neg", "imp"] },
    { id: "wish", label: "희망형", meaning: "~하고 싶다", category: "will", wrong: ["caus_wish", "wish_past", "vol"] },
    { id: "appear", label: "양태형", meaning: "~할 것 같아보인다", category: "will", wrong: ["wish", "masu", "past"] },

  // ── 사역&수동 ──
    { id: "pot", label: "가능형", meaning: "~할 수 있다", category: "passive", wrong: ["pass", "caus", "imp"] },
    { id: "pass", label: "수동형", meaning: "~당하다, ~받다", category: "passive", wrong: ["caus", "caus_pass", "pot"] },
    { id: "must", label: "의무형", meaning: "~해야 한다", category: "passive", wrong: ["cond_neg", "neg", "neg_zu"] },
    { id: "neg_zu", label: "특수부정형", meaning: "~하지 않고", category: "passive", wrong: ["neg", "must", "past_neg"] },
    { id: "caus", label: "사역형", meaning: "~시키다, ~하게 하다", category: "passive", wrong: ["pass", "caus_pass", "pot"] },

  // ── 보조 동사 ──
    { id: "prep", label: "준비형", meaning: "~해두다", category: "aux", wrong: ["try", "prog", "te"] },
    { id: "try", label: "시도형", meaning: "~해보다", category: "aux", wrong: ["prog", "prep", "excess"] },
    { id: "excess", label: "과도형", meaning: "너무 ~하다", category: "aux", wrong: ["appear", "wish", "masu"] },

  // ── 결합 변형 ──
    { id: "past_neg", label: "과거부정형", meaning: "~하지 않았다", category: "adv", wrong: ["past", "neg", "wish_past"] },
    { id: "caus_pass", label: "사역수동형", meaning: "~하게 당하다", category: "adv", wrong: ["caus", "pass", "caus_wish"] },
    { id: "caus_wish", label: "사역희망형", meaning: "~시키고 싶다", category: "adv", wrong: ["wish", "caus", "caus_pass"] },
    { id: "prog_neg", label: "진행부정형", meaning: "~하고 있지 않다", category: "adv", wrong: ["prog", "pot_neg", "prog_past"] },
    { id: "prog_past", label: "진행과거형", meaning: "~하고 있었다", category: "adv", wrong: ["prog", "past", "prog_neg"] },
    { id: "pot_neg", label: "가능부정형", meaning: "~할 수 없다", category: "adv", wrong: ["neg", "pot", "cond_neg"] },
    { id: "cond_neg", label: "가정부정형", meaning: "~하지 않는다면", category: "adv", wrong: ["cond_ba", "must", "neg"] },
    { id: "wish_past", label: "희망과거형", meaning: "~하고 싶었다", category: "adv", wrong: ["wish", "past", "past_neg"] }
];

const conjVerbs = [
    {
    word: "会う",
    reading: "あう",
    meaning: "만나다",
    group: 1,
    forms: {
      masu: "あいます",
      i: "あい",
      te: "あって",
      neg: "あわない",
      past: "あった",
      prog: "あっている",
      cond_ba: "あえば",
      cond_tara: "あったら",
      cond_to: "あうと",
      cond_nara: "あうなら",
      wish: "あいたい",
      vol: "あおう",
      imp: "あえ",
      prohib: "あうな",
      appear: "あいそうだ",
      pot: "あえる",
      pass: "あわれる",
      caus: "あわせる",
      must: "あわなければならない",
      neg_zu: "あわずに",
      prep: "あっておく",
      try: "あってみる",
      excess: "あいすぎる",
      past_neg: "あわなかった",
      caus_pass: "あわせられる",
      caus_wish: "あわせたい",
      prog_neg: "あっていない",
      prog_past: "あっていた",
      pot_neg: "あえない",
      cond_neg: "あわなければ",
      wish_past: "あいたかった"
    }
  },
    {
    word: "買う",
    reading: "かう",
    meaning: "사다",
    group: 1,
    forms: {
      masu: "かいます",
      i: "かい",
      te: "かって",
      neg: "かわない",
      past: "かった",
      prog: "かっている",
      cond_ba: "かえば",
      cond_tara: "かったら",
      cond_to: "かうと",
      cond_nara: "かうなら",
      wish: "かいたい",
      vol: "かおう",
      imp: "かえ",
      prohib: "かうな",
      appear: "かいそうだ",
      pot: "かえる",
      pass: "かわれる",
      caus: "かわせる",
      must: "かわなければならない",
      neg_zu: "かわずに",
      prep: "かっておく",
      try: "かってみる",
      excess: "かいすぎる",
      past_neg: "かわなかった",
      caus_pass: "かわせられる",
      caus_wish: "かわせたい",
      prog_neg: "かっていない",
      prog_past: "かっていた",
      pot_neg: "かえない",
      cond_neg: "かわなければ",
      wish_past: "かいたかった"
    }
  },
    {
    word: "貰う",
    reading: "もらう",
    meaning: "받다",
    group: 1,
    forms: {
      masu: "もらいます",
      i: "もらい",
      te: "もらって",
      neg: "もらわない",
      past: "もらった",
      prog: "もらっている",
      cond_ba: "もらえば",
      cond_tara: "もらったら",
      cond_to: "もらうと",
      cond_nara: "もらうなら",
      wish: "もらいたい",
      vol: "もらおう",
      imp: "もらえ",
      prohib: "もらうな",
      appear: "もらいそうだ",
      pot: "もらえる",
      pass: "もらわれる",
      caus: "もらわせる",
      must: "もらわなければならない",
      neg_zu: "もらわずに",
      prep: "もらっておく",
      try: "もらってみる",
      excess: "もらいすぎる",
      past_neg: "もらわなかった",
      caus_pass: "もらわせられる",
      caus_wish: "もらわせたい",
      prog_neg: "もらっていない",
      prog_past: "もらっていた",
      pot_neg: "もらえない",
      cond_neg: "もらわなければ",
      wish_past: "もらいたかった"
    }
  },
  {
    word: "仕舞う",
    reading: "しまう",
    meaning: "해버리다",
    group: 1,
    forms: {
      masu: "しまいます",
      i: "しまい",
      te: "しまって",
      neg: "しまわない",
      past: "しまった",
      prog: "しまっている",
      cond_ba: "しまえば",
      cond_tara: "しまったら",
      cond_to: "しまうと",
      cond_nara: "しまうなら",
      wish: "しまいたい",
      vol: "しまおう",
      imp: "しまえ",
      prohib: "しまうな",
      appear: "しまいそうだ",
      pot: "しまえる",
      pass: "しまわれる",
      caus: "しまわせる",
      must: "しまわなければならない",
      neg_zu: "しまわずに",
      prep: "しまっておく",
      try: "しまってみる",
      excess: "しまいすぎる",
      past_neg: "しまわなかった",
      caus_pass: "しまわせられる",
      caus_wish: "しまわせたい",
      prog_neg: "しまっていない",
      prog_past: "しまっていた",
      pot_neg: "しまえない",
      cond_neg: "しまわなければ",
      wish_past: "しまいたかった"
    }
  },
  {
    word: "書く",
    reading: "かく",
    meaning: "쓰다",
    group: 1,
    forms: {
      masu: "かきます",
      i: "かき",
      te: "かいて",
      neg: "かかない",
      past: "かいた",
      prog: "かいている",
      cond_ba: "かけば",
      cond_tara: "かいたら",
      cond_to: "かくと",
      cond_nara: "かくなら",
      wish: "かきたい",
      vol: "かこう",
      imp: "かけ",
      prohib: "かくな",
      appear: "かきそうだ",
      pot: "かける",
      pass: "かかれる",
      caus: "かかせる",
      must: "かかなければならない",
      neg_zu: "かかずに",
      prep: "かいておく",
      try: "かいてみる",
      excess: "かきすぎる",
      past_neg: "かかなかった",
      caus_pass: "かかせられる",
      caus_wish: "かかせたい",
      prog_neg: "かいていない",
      prog_past: "かいていた",
      pot_neg: "かけない",
      cond_neg: "かかなければ",
      wish_past: "かきたかった"
    }
  },
  {
    word: "行く",
    reading: "いく",
    meaning: "가다",
    group: 1,
    forms: {
      masu: "いきます",
      i: "いき",
      te: "いって",
      neg: "いかない",
      past: "いった",
      prog: "いっている",
      cond_ba: "いけば",
      cond_tara: "いったら",
      cond_to: "いくと",
      cond_nara: "いくなら",
      wish: "いきたい",
      vol: "いこう",
      imp: "いけ",
      prohib: "いくな",
      appear: "いきそうだ",
      pot: "いける",
      pass: "いかれる",
      caus: "いかせる",
      must: "いかなければならない",
      neg_zu: "いかずに",
      prep: "いっておく",
      try: "いってみる",
      excess: "いきすぎる",
      past_neg: "いかなかった",
      caus_pass: "いかせられる",
      caus_wish: "いかせたい",
      prog_neg: "いっていない",
      prog_past: "いっていた",
      pot_neg: "いけない",
      cond_neg: "いかなければ",
      wish_past: "いきたかった"
    }
  },
  {
    word: "置く",
    reading: "おく",
    meaning: "두다",
    group: 1,
    forms: {
      masu: "おきます",
      i: "おき",
      te: "おいて",
      neg: "おかない",
      past: "おいた",
      prog: "おいている",
      cond_ba: "おけば",
      cond_tara: "おいたら",
      cond_to: "おくと",
      cond_nara: "おくなら",
      wish: "おきたい",
      vol: "おこう",
      imp: "おけ",
      prohib: "おくな",
      appear: "おきそうだ",
      pot: "おける",
      pass: "おかれる",
      caus: "おかせる",
      must: "おかなければならない",
      neg_zu: "おかずに",
      prep: "おいておく",
      try: "おいてみる",
      excess: "おきすぎる",
      past_neg: "おかなかった",
      caus_pass: "おかせられる",
      caus_wish: "おかせたい",
      prog_neg: "おいていない",
      prog_past: "おいていた",
      pot_neg: "おけない",
      cond_neg: "おかなければ",
      wish_past: "おきたかった"
    }
  },
  {
    word: "話す",
    reading: "はなす",
    meaning: "말하다",
    group: 1,
    forms: {
      masu: "はなします",
      i: "はなし",
      te: "はなして",
      neg: "はなさない",
      past: "はなした",
      prog: "はなしている",
      cond_ba: "はなせば",
      cond_tara: "はなしたら",
      cond_to: "はなすと",
      cond_nara: "はなすなら",
      wish: "はなしたい",
      vol: "はなそう",
      imp: "はなせ",
      prohib: "はなすな",
      appear: "はなしそうだ",
      pot: "はなせる",
      pass: "はなされる",
      caus: "はなさせる",
      must: "はなさなければならない",
      neg_zu: "はなさずに",
      prep: "はなしておく",
      try: "はなしてみる",
      excess: "はなしすぎる",
      past_neg: "はなさなかった",
      caus_pass: "はなさせられる",
      caus_wish: "はなさせたい",
      prog_neg: "はなしていない",
      prog_past: "はなしていた",
      pot_neg: "はなせない",
      cond_neg: "はなさなければ",
      wish_past: "はなしたかった"
    }
  },
  {
    word: "待つ",
    reading: "まつ",
    meaning: "기다리다",
    group: 1,
    forms: {
      masu: "まちます",
      i: "まち",
      te: "まって",
      neg: "またない",
      past: "まった",
      prog: "まっている",
      cond_ba: "まてば",
      cond_tara: "まったら",
      cond_to: "まつと",
      cond_nara: "まつなら",
      wish: "まちたい",
      vol: "まとう",
      imp: "まて",
      prohib: "まつな",
      appear: "まちそうだ",
      pot: "まてる",
      pass: "またれる",
      caus: "またせる",
      must: "またなければならない",
      neg_zu: "またずに",
      prep: "まっておく",
      try: "まってみる",
      excess: "まちすぎる",
      past_neg: "またなかった",
      caus_pass: "またせられる",
      caus_wish: "またせたい",
      prog_neg: "まっていない",
      prog_past: "まっていた",
      pot_neg: "まてない",
      cond_neg: "またなければ",
      wish_past: "まちたかった"
    }
  },
  {
    word: "飲む",
    reading: "のむ",
    meaning: "마시다",
    group: 1,
    forms: {
      masu: "のみます",
      i: "のみ",
      te: "のんで",
      neg: "のまない",
      past: "のんだ",
      prog: "のんでいる",
      cond_ba: "のめば",
      cond_tara: "のんだら",
      cond_to: "のむと",
      cond_nara: "のむなら",
      wish: "のみたい",
      vol: "のもう",
      imp: "のめ",
      prohib: "のむな",
      appear: "のみそうだ",
      pot: "のめる",
      pass: "のまれる",
      caus: "のませる",
      must: "のまなければならない",
      neg_zu: "のまずに",
      prep: "のんでおく",
      try: "のんでみる",
      excess: "のみすぎる",
      past_neg: "のまなかった",
      caus_pass: "のませられる",
      caus_wish: "のませたい",
      prog_neg: "のんでいない",
      prog_past: "のんでいた",
      pot_neg: "のめない",
      cond_neg: "のまなければ",
      wish_past: "のみたかった"
    }
  },
  {
    word: "作る",
    reading: "つくる",
    meaning: "만들다",
    group: 1,
    forms: {
      masu: "つくります",
      i: "つくり",
      te: "つくって",
      neg: "つくらない",
      past: "つくった",
      prog: "つくっている",
      cond_ba: "つくれば",
      cond_tara: "つくったら",
      cond_to: "つくると",
      cond_nara: "つくるなら",
      wish: "つくりたい",
      vol: "つくろう",
      imp: "つくれ",
      prohib: "つくるな",
      appear: "つくりそうだ",
      pot: "つくれる",
      pass: "つくられる",
      caus: "つくらせる",
      must: "つくらなければならない",
      neg_zu: "つくらずに",
      prep: "つくっておく",
      try: "つくってみる",
      excess: "つくりすぎる",
      past_neg: "つくらなかった",
      caus_pass: "つくらせられる",
      caus_wish: "つくらせたい",
      prog_neg: "つくっていない",
      prog_past: "つくっていた",
      pot_neg: "つくれない",
      cond_neg: "つくらなければ",
      wish_past: "つくりたかった"
    }
  },
  {
    word: "送る",
    reading: "おくる",
    meaning: "보내다",
    group: 1,
    forms: {
      masu: "おくります",
      i: "おくり",
      te: "おくって",
      neg: "おくらない",
      past: "おくった",
      prog: "おくっている",
      cond_ba: "おくれば",
      cond_tara: "おくったら",
      cond_to: "おくると",
      cond_nara: "おくるなら",
      wish: "おくりたい",
      vol: "おくろう",
      imp: "おくれ",
      prohib: "おくるな",
      appear: "おくりそうだ",
      pot: "おくれる",
      pass: "おくられる",
      caus: "おくらせる",
      must: "おくらなければならない",
      neg_zu: "おくらずに",
      prep: "おくっておく",
      try: "おくってみる",
      excess: "おくりすぎる",
      past_neg: "おくらなかった",
      caus_pass: "おくらせられる",
      caus_wish: "おくらせたい",
      prog_neg: "おくっていない",
      prog_past: "おくっていた",
      pot_neg: "おくれない",
      cond_neg: "おくらなければ",
      wish_past: "おくりたかった"
    }
  },
  {
    word: "終わる",
    reading: "おわる",
    meaning: "끝내다",
    group: 1,
    forms: {
      masu: "おわります",
      i: "おわり",
      te: "おわって",
      neg: "おわらない",
      past: "おわった",
      prog: "おわっている",
      cond_ba: "おわれば",
      cond_tara: "おわったら",
      cond_to: "おわると",
      cond_nara: "おわるなら",
      wish: "おわりたい",
      vol: "おわろう",
      imp: "おわれ",
      prohib: "おわるな",
      appear: "おわりそうだ",
      pot: "おわれる",
      pass: "おわられる",
      caus: "おわらせる",
      must: "おわらなければならない",
      neg_zu: "おわらずに",
      prep: "おわっておく",
      try: "おわってみる",
      excess: "おわりすぎる",
      past_neg: "おわらなかった",
      caus_pass: "おわらせられる",
      caus_wish: "おわらせたい",
      prog_neg: "おわっていない",
      prog_past: "おわっていた",
      pot_neg: "おわれない",
      cond_neg: "おわらなければ",
      wish_past: "おわりたかった"
    }
  },
  {
    word: "要る",
    reading: "いる",
    meaning: "필요하다",
    group: 1,
    forms: {
      masu: "いります",
      i: "いり",
      te: "いって",
      neg: "いらない",
      past: "いった",
      prog: "いっている",
      cond_ba: "いれば",
      cond_tara: "いったら",
      cond_to: "いると",
      cond_nara: "いるなら",
      wish: "いりたい",
      vol: "いろう",
      imp: "いれ",
      prohib: "いるな",
      appear: "いりそうだ",
      pot: "いれる",
      pass: "いられる",
      caus: "いらせる",
      must: "いらなければならない",
      neg_zu: "いらずに",
      prep: "いっておく",
      try: "いってみる",
      excess: "いりすぎる",
      past_neg: "いらなかった",
      caus_pass: "いらせられる",
      caus_wish: "いらせたい",
      prog_neg: "いっていない",
      prog_past: "いっていた",
      pot_neg: "いれない",
      cond_neg: "いらなければ",
      wish_past: "いりたかった"
    }
  },
  {
    word: "帰る",
    reading: "かえる",
    meaning: "돌아가다",
    group: 1,
    forms: {
      masu: "かえります",
      i: "かえり",
      te: "かえって",
      neg: "かえらない",
      past: "かえった",
      prog: "かえっている",
      cond_ba: "かえれば",
      cond_tara: "かえったら",
      cond_to: "かえると",
      cond_nara: "かえるなら",
      wish: "かえりたい",
      vol: "かえろう",
      imp: "かえれ",
      prohib: "かえるな",
      appear: "かえりそうだ",
      pot: "かえれる",
      pass: "かえられる",
      caus: "かえらせる",
      must: "かえらなければならない",
      neg_zu: "かえらずに",
      prep: "かえっておく",
      try: "かえってみる",
      excess: "かえりすぎる",
      past_neg: "かえらなかった",
      caus_pass: "かえらせられる",
      caus_wish: "かえらせたい",
      prog_neg: "かえっていない",
      prog_past: "かえっていた",
      pot_neg: "かえれない",
      cond_neg: "かえらなければ",
      wish_past: "かえりたかった"
    }
  },
  {
    word: "入る",
    reading: "はいる",
    meaning: "들어가다",
    group: 1,
    forms: {
      masu: "はいります",
      i: "はいり",
      te: "はいって",
      neg: "はいらない",
      past: "はいった",
      prog: "はいっている",
      cond_ba: "はいれば",
      cond_tara: "はいったら",
      cond_to: "はいると",
      cond_nara: "はいるなら",
      wish: "はいりたい",
      vol: "はいろう",
      imp: "はいれ",
      prohib: "はいるな",
      appear: "はいりそうだ",
      pot: "はいれる",
      pass: "はいられる",
      caus: "はいらせる",
      must: "はいらなければならない",
      neg_zu: "はいらずに",
      prep: "はいっておく",
      try: "はいってみる",
      excess: "はいりすぎる",
      past_neg: "はいらなかった",
      caus_pass: "はいらせられる",
      caus_wish: "はいらせたい",
      prog_neg: "はいっていない",
      prog_past: "はいっていた",
      pot_neg: "はいれない",
      cond_neg: "はいらなければ",
      wish_past: "はいりたかった"
    }
  },
  {
    word: "走る",
    reading: "はしる",
    meaning: "달리다",
    group: 1,
    forms: {
      masu: "はしります",
      i: "はしり",
      te: "はしって",
      neg: "はしらない",
      past: "はしった",
      prog: "はしっている",
      cond_ba: "はしれば",
      cond_tara: "はしったら",
      cond_to: "はしると",
      cond_nara: "はしるなら",
      wish: "はしりたい",
      vol: "はしろう",
      imp: "はしれ",
      prohib: "はしるな",
      appear: "はしりそうだ",
      pot: "はしれる",
      pass: "はしられる",
      caus: "はしらせる",
      must: "はしらなければならない",
      neg_zu: "はしらずに",
      prep: "はしっておく",
      try: "はしってみる",
      excess: "はしりすぎる",
      past_neg: "はしらなかった",
      caus_pass: "はしらせられる",
      caus_wish: "はしらせたい",
      prog_neg: "はしっていない",
      prog_past: "はしっていた",
      pot_neg: "はしれない",
      cond_neg: "はしらなければ",
      wish_past: "はしりたかった"
    }
  },
  {
    word: "知る",
    reading: "しる",
    meaning: "알다",
    group: 1,
    forms: {
      masu: "しります",
      i: "しり",
      te: "しって",
      neg: "しらない",
      past: "しった",
      prog: "しっている",
      cond_ba: "しれば",
      cond_tara: "しったら",
      cond_to: "しると",
      cond_nara: "しるなら",
      wish: "しりたい",
      vol: "しろう",
      imp: "しれ",
      prohib: "しるな",
      appear: "しりそうだ",
      pot: "しれる",
      pass: "しられる",
      caus: "しらせる",
      must: "しらなければならない",
      neg_zu: "しらずに",
      prep: "しっておく",
      try: "しってみる",
      excess: "しりすぎる",
      past_neg: "しらなかった",
      caus_pass: "しらせられる",
      caus_wish: "しらせたい",
      prog_neg: "しっていない",
      prog_past: "しっていた",
      pot_neg: "しれない",
      cond_neg: "しらなければ",
      wish_past: "しりたかった"
    }
  },
  {
    word: "切る",
    reading: "きる",
    meaning: "자르다",
    group: 1,
    forms: {
      masu: "きります",
      i: "きり",
      te: "きって",
      neg: "きらない",
      past: "きった",
      prog: "きっている",
      cond_ba: "きれば",
      cond_tara: "きったら",
      cond_to: "きると",
      cond_nara: "きるなら",
      wish: "きりたい",
      vol: "きろう",
      imp: "きれ",
      prohib: "きるな",
      appear: "きりそうだ",
      pot: "きれる",
      pass: "きられる",
      caus: "きらせる",
      must: "きらなければならない",
      neg_zu: "きらずに",
      prep: "きっておく",
      try: "きってみる",
      excess: "きりすぎる",
      past_neg: "きらなかった",
      caus_pass: "きらせられる",
      caus_wish: "きらせたい",
      prog_neg: "きっていない",
      prog_past: "きっていた",
      pot_neg: "きれない",
      cond_neg: "きらなければ",
      wish_past: "きりたかった"
    }
  },
  {
    word: "喋る",
    reading: "しゃべる",
    meaning: "수다떨다",
    group: 1,
    forms: {
      masu: "しゃべります",
      i: "しゃべり",
      te: "しゃべって",
      neg: "しゃべらない",
      past: "しゃべった",
      prog: "しゃべっている",
      cond_ba: "しゃべれば",
      cond_tara: "しゃべったら",
      cond_to: "しゃべると",
      cond_nara: "しゃべるなら",
      wish: "しゃべりたい",
      vol: "しゃべろう",
      imp: "しゃべれ",
      prohib: "しゃべるな",
      appear: "しゃべりそうだ",
      pot: "しゃべれる",
      pass: "しゃべられる",
      caus: "しゃべらせる",
      must: "しゃべらなければならない",
      neg_zu: "しゃべらずに",
      prep: "しゃべっておく",
      try: "しゃべってみる",
      excess: "しゃべりすぎる",
      past_neg: "しゃべらなかった",
      caus_pass: "しゃべらせられる",
      caus_wish: "しゃべらせたい",
      prog_neg: "しゃべっていない",
      prog_past: "しゃべっていた",
      pot_neg: "しゃべれない",
      cond_neg: "しゃべらなければ",
      wish_past: "しゃべりたかった"
    }
  },
  {
    word: "参る",
    reading: "まいる",
    meaning: "가다, 오다",
    group: 1,
    forms: {
      masu: "まいります",
      i: "まいり",
      te: "まいって",
      neg: "まいらない",
      past: "まいった",
      prog: "まいっている",
      cond_ba: "まいれば",
      cond_tara: "まいったら",
      cond_to: "まいると",
      cond_nara: "まいるなら",
      wish: "まいりたい",
      vol: "まいろう",
      imp: "まいれ",
      prohib: "まいるな",
      appear: "まいりそうだ",
      pot: "まいれる",
      pass: "まいられる",
      caus: "まいらせる",
      must: "まいらなければならない",
      neg_zu: "まいらずに",
      prep: "まいっておく",
      try: "まいってみる",
      excess: "まいりすぎる",
      past_neg: "まいらなかった",
      caus_pass: "まいらせられる",
      caus_wish: "まいらせたい",
      prog_neg: "まいっていない",
      prog_past: "まいっていた",
      pot_neg: "まいれない",
      cond_neg: "まいらなければ",
      wish_past: "まいりたかった"
    }
  },
  {
    word: "限る",
    reading: "かぎる",
    meaning: "한정하다",
    group: 1,
    forms: {
      masu: "かぎります",
      i: "かぎり",
      te: "かぎって",
      neg: "かぎらない",
      past: "かぎった",
      prog: "かぎっている",
      cond_ba: "かぎれば",
      cond_tara: "かぎったら",
      cond_to: "かぎると",
      cond_nara: "かぎるなら",
      wish: "かぎりたい",
      vol: "かぎろう",
      imp: "かぎれ",
      prohib: "かぎるな",
      appear: "かぎりそうだ",
      pot: "かぎれる",
      pass: "かぎられる",
      caus: "かぎらせる",
      must: "かぎらなければならない",
      neg_zu: "かぎらずに",
      prep: "かぎっておく",
      try: "かぎってみる",
      excess: "かぎりすぎる",
      past_neg: "かぎらなかった",
      caus_pass: "かぎらせられる",
      caus_wish: "かぎらせたい",
      prog_neg: "かぎっていない",
      prog_past: "かぎっていた",
      pot_neg: "かぎれない",
      cond_neg: "かぎらなければ",
      wish_past: "かぎりたかった"
    }
  },
  {
    word: "蹴る",
    reading: "ける",
    meaning: "차다",
    group: 1,
    forms: {
      masu: "けります",
      i: "けり",
      te: "けって",
      neg: "けらない",
      past: "けった",
      prog: "けっている",
      cond_ba: "ければ",
      cond_tara: "けったら",
      cond_to: "けると",
      cond_nara: "けるなら",
      wish: "けりたい",
      vol: "けろう",
      imp: "けれ",
      prohib: "けるな",
      appear: "けりそうだ",
      pot: "けれる",
      pass: "けられる",
      caus: "けらせる",
      must: "けらなければならない",
      neg_zu: "けらずに",
      prep: "けっておく",
      try: "けってみる",
      excess: "けりすぎる",
      past_neg: "けらなかった",
      caus_pass: "けらせられる",
      caus_wish: "けらせたい",
      prog_neg: "けっていない",
      prog_past: "けっていた",
      pot_neg: "けれない",
      cond_neg: "けらなければ",
      wish_past: "けりたかった"
    }
  },
  {
    word: "滑る",
    reading: "すべる",
    meaning: "미끄러지다",
    group: 1,
    forms: {
      masu: "すべります",
      i: "すべり",
      te: "すべって",
      neg: "すべらない",
      past: "すべった",
      prog: "すべっている",
      cond_ba: "すべれば",
      cond_tara: "すべったら",
      cond_to: "すべると",
      cond_nara: "すべるなら",
      wish: "すべりたい",
      vol: "すべろう",
      imp: "すべれ",
      prohib: "すべるな",
      appear: "すべりそうだ",
      pot: "すべれる",
      pass: "すべられる",
      caus: "すべらせる",
      must: "すべらなければならない",
      neg_zu: "すべらずに",
      prep: "すべっておく",
      try: "すべってみる",
      excess: "すべりすぎる",
      past_neg: "すべらなかった",
      caus_pass: "すべらせられる",
      caus_wish: "すべらせたい",
      prog_neg: "すべっていない",
      prog_past: "すべっていた",
      pot_neg: "すべれない",
      cond_neg: "すべらなければ",
      wish_past: "すべりたかった"
    }
  },
  {
    word: "食べる",
    reading: "たべる",
    meaning: "먹다",
    group: 2,
    forms: {
      masu: "たべます",
      i: "たべ",
      te: "たべて",
      neg: "たべない",
      past: "たべた",
      prog: "たべている",
      cond_ba: "たべれば",
      cond_tara: "たべたら",
      cond_to: "たべると",
      cond_nara: "たべるなら",
      wish: "たべたい",
      vol: "たべよう",
      imp: "たべろ",
      prohib: "たべるな",
      appear: "たべそうだ",
      pot: "たべられる",
      pass: "たべられる",
      caus: "たべさせる",
      must: "たべなければならない",
      neg_zu: "たべずに",
      prep: "たべておく",
      try: "たべてみる",
      excess: "たべすぎる",
      past_neg: "たべなかった",
      caus_pass: "たべさせられる",
      caus_wish: "たべさせたい",
      prog_neg: "たべていない",
      prog_past: "たべていた",
      pot_neg: "たべられない",
      cond_neg: "たべなければ",
      wish_past: "たべたかった"
    }
  },
  {
    word: "寝る",
    reading: "ねる",
    meaning: "자다",
    group: 2,
    forms: {
      masu: "ねます",
      i: "ね",
      te: "ねて",
      neg: "ねない",
      past: "ねた",
      prog: "ねている",
      cond_ba: "ねれば",
      cond_tara: "ねたら",
      cond_to: "ねると",
      cond_nara: "ねるなら",
      wish: "ねたい",
      vol: "ねよう",
      imp: "ねろ",
      prohib: "ねるな",
      appear: "ねそうだ",
      pot: "ねられる",
      pass: "ねられる",
      caus: "ねさせる",
      must: "ねなければならない",
      neg_zu: "ねずに",
      prep: "ねておく",
      try: "ねてみる",
      excess: "ねすぎる",
      past_neg: "ねなかった",
      caus_pass: "ねさせられる",
      caus_wish: "ねさせたい",
      prog_neg: "ねていない",
      prog_past: "ねていた",
      pot_neg: "ねられない",
      cond_neg: "ねなければ",
      wish_past: "ねたかった"
    }
  },
  {
    word: "上げる",
    reading: "あげる",
    meaning: "주다",
    group: 2,
    forms: {
      masu: "あげます",
      i: "あげ",
      te: "あげて",
      neg: "あげない",
      past: "あげた",
      prog: "あげている",
      cond_ba: "あげれば",
      cond_tara: "あげたら",
      cond_to: "あげると",
      cond_nara: "あげるなら",
      wish: "あげたい",
      vol: "あげよう",
      imp: "あげろ",
      prohib: "あげるな",
      appear: "あげそうだ",
      pot: "あげられる",
      pass: "あげられる",
      caus: "あげさせる",
      must: "あげなければならない",
      neg_zu: "あげずに",
      prep: "あげておく",
      try: "あげてみる",
      excess: "あげすぎる",
      past_neg: "あげなかった",
      caus_pass: "あげさせられる",
      caus_wish: "あげさせたい",
      prog_neg: "あげていない",
      prog_past: "あげていた",
      pot_neg: "あげられない",
      cond_neg: "あげなければ",
      wish_past: "あげたかった"
    }
  },
  {
    word: "呉れる",
    reading: "くれる",
    meaning: "주다",
    group: 2,
    forms: {
      masu: "くれます",
      i: "くれ",
      te: "くれて",
      neg: "くれない",
      past: "くれた",
      prog: "くれている",
      cond_ba: "くれれば",
      cond_tara: "くれたら",
      cond_to: "くれると",
      cond_nara: "くれるなら",
      wish: "くれたい",
      vol: "くれよう",
      imp: "くれろ",
      prohib: "くれるな",
      appear: "くれそうだ",
      pot: "くれられる",
      pass: "くれられる",
      caus: "くれさせる",
      must: "くれなければならない",
      neg_zu: "くれずに",
      prep: "くれておく",
      try: "くれてみる",
      excess: "くれすぎる",
      past_neg: "くれなかった",
      caus_pass: "くれさせられる",
      caus_wish: "くれさせたい",
      prog_neg: "くれていない",
      prog_past: "くれていた",
      pot_neg: "くれられない",
      cond_neg: "くれなければ",
      wish_past: "くれたかった"
    }
  },
  {
    word: "起きる",
    reading: "おきる",
    meaning: "일어나다",
    group: 2,
    forms: {
      masu: "おきます",
      i: "おき",
      te: "おきて",
      neg: "おきない",
      past: "おきた",
      prog: "おきている",
      cond_ba: "おきれば",
      cond_tara: "おきたら",
      cond_to: "おきると",
      cond_nara: "おきるなら",
      wish: "おきたい",
      vol: "おきよう",
      imp: "おきろ",
      prohib: "おきるな",
      appear: "おきそうだ",
      pot: "おきられる",
      pass: "おきられる",
      caus: "おきさせる",
      must: "おきなければならない",
      neg_zu: "おきずに",
      prep: "おきておく",
      try: "おきてみる",
      excess: "おきすぎる",
      past_neg: "おきなかった",
      caus_pass: "おきさせられる",
      caus_wish: "おきさせたい",
      prog_neg: "おきていない",
      prog_past: "おきていた",
      pot_neg: "おきられない",
      cond_neg: "おきなければ",
      wish_past: "おきたかった"
    }
  },
  {
    word: "見る",
    reading: "みる",
    meaning: "보다",
    group: 2,
    forms: {
      masu: "みます",
      i: "み",
      te: "みて",
      neg: "みない",
      past: "みた",
      prog: "みている",
      cond_ba: "みれば",
      cond_tara: "みたら",
      cond_to: "みると",
      cond_nara: "みるなら",
      wish: "みたい",
      vol: "みよう",
      imp: "みろ",
      prohib: "みるな",
      appear: "みそうだ",
      pot: "みられる",
      pass: "みられる",
      caus: "みさせる",
      must: "みなければならない",
      neg_zu: "みずに",
      prep: "みておく",
      try: "みてみる",
      excess: "みすぎる",
      past_neg: "みなかった",
      caus_pass: "みさせられる",
      caus_wish: "みさせたい",
      prog_neg: "みていない",
      prog_past: "みていた",
      pot_neg: "みられない",
      cond_neg: "みなければ",
      wish_past: "みたかった"
    }
  },
  {
    word: "教える",
    reading: "おしえる",
    meaning: "가르치다",
    group: 2,
    forms: {
      masu: "おしえます",
      i: "おしえ",
      te: "おしえて",
      neg: "おしえない",
      past: "おしえた",
      prog: "おしえている",
      cond_ba: "おしえれば",
      cond_tara: "おしえたら",
      cond_to: "おしえると",
      cond_nara: "おしえるなら",
      wish: "おしえたい",
      vol: "おしえよう",
      imp: "おしえろ",
      prohib: "おしえるな",
      appear: "おしえそうだ",
      pot: "おしえられる",
      pass: "おしえられる",
      caus: "おしえさせる",
      must: "おしえなければならない",
      neg_zu: "おしえずに",
      prep: "おしえておく",
      try: "おしえてみる",
      excess: "おしえすぎる",
      past_neg: "おしえなかった",
      caus_pass: "おしえさせられる",
      caus_wish: "おしえさせたい",
      prog_neg: "おしえていない",
      prog_past: "おしえていた",
      pot_neg: "おしえられない",
      cond_neg: "おしえなければ",
      wish_past: "おしえたかった"
    }
  },
  {
    word: "忘れる",
    reading: "わすれる",
    meaning: "잊다",
    group: 2,
    forms: {
      masu: "わすれます",
      i: "わすれ",
      te: "わすれて",
      neg: "わすれない",
      past: "わすれた",
      prog: "わすれている",
      cond_ba: "わすれれば",
      cond_tara: "わすれたら",
      cond_to: "わすれると",
      cond_nara: "わすれるなら",
      wish: "わすれたい",
      vol: "わすれよう",
      imp: "わすれろ",
      prohib: "わすれるな",
      appear: "わすれそうだ",
      pot: "わすれられる",
      pass: "わすれられる",
      caus: "わすれさせる",
      must: "わすれなければならない",
      neg_zu: "わすれずに",
      prep: "わすれておく",
      try: "わすれてみる",
      excess: "わすれすぎる",
      past_neg: "わすれなかった",
      caus_pass: "わすれさせられる",
      caus_wish: "わすれさせたい",
      prog_neg: "わすれていない",
      prog_past: "わすれていた",
      pot_neg: "わすれられない",
      cond_neg: "わすれなければ",
      wish_past: "わすれたかった"
    }
  },
  {
    word: "開ける",
    reading: "あける",
    meaning: "열다",
    group: 2,
    forms: {
      masu: "あけます",
      i: "あけ",
      te: "あけて",
      neg: "あけない",
      past: "あけた",
      prog: "あけている",
      cond_ba: "あければ",
      cond_tara: "あけたら",
      cond_to: "あけると",
      cond_nara: "あけるなら",
      wish: "あけたい",
      vol: "あけよう",
      imp: "あけろ",
      prohib: "あけるな",
      appear: "あけそうだ",
      pot: "あけられる",
      pass: "あけられる",
      caus: "あけさせる",
      must: "あけなければならない",
      neg_zu: "あけずに",
      prep: "あけておく",
      try: "あけてみる",
      excess: "あけすぎる",
      past_neg: "あけなかった",
      caus_pass: "あけさせられる",
      caus_wish: "あけさせたい",
      prog_neg: "あけていない",
      prog_past: "あけていた",
      pot_neg: "あけられない",
      cond_neg: "あけなければ",
      wish_past: "あけたかった"
    }
  },
  {
    word: "落ちる",
    reading: "おちる",
    meaning: "떨어지다",
    group: 2,
    forms: {
      masu: "おちます",
      i: "おち",
      te: "おちて",
      neg: "おちない",
      past: "おちた",
      prog: "おちている",
      cond_ba: "おちれば",
      cond_tara: "おちたら",
      cond_to: "おちると",
      cond_nara: "おちるなら",
      wish: "おちたい",
      vol: "おちよう",
      imp: "おちろ",
      prohib: "おちるな",
      appear: "おちそうだ",
      pot: "おちられる",
      pass: "おちられる",
      caus: "おちさせる",
      must: "おちなければならない",
      neg_zu: "おちずに",
      prep: "おちておく",
      try: "おちてみる",
      excess: "おちすぎる",
      past_neg: "おちなかった",
      caus_pass: "おちさせられる",
      caus_wish: "おちさせたい",
      prog_neg: "おちていない",
      prog_past: "おちていた",
      pot_neg: "おちられない",
      cond_neg: "おちなければ",
      wish_past: "おちたかった"
    }
  },
  {
    word: "変える",
    reading: "かえる",
    meaning: "바꾸다",
    group: 2,
    forms: {
      masu: "かえます",
      i: "かえ",
      te: "かえて",
      neg: "かえない",
      past: "かえた",
      prog: "かえている",
      cond_ba: "かえれば",
      cond_tara: "かえたら",
      cond_to: "かえると",
      cond_nara: "かえるなら",
      wish: "かえたい",
      vol: "かえよう",
      imp: "かえろ",
      prohib: "かえるな",
      appear: "かえそうだ",
      pot: "かえられる",
      pass: "かえられる",
      caus: "かえさせる",
      must: "かえなければならない",
      neg_zu: "かえずに",
      prep: "かえておく",
      try: "かえてみる",
      excess: "かえすぎる",
      past_neg: "かえなかった",
      caus_pass: "かえさせられる",
      caus_wish: "かえさせたい",
      prog_neg: "かえていない",
      prog_past: "かえていた",
      pot_neg: "かえられない",
      cond_neg: "かえなければ",
      wish_past: "かえたかった"
    }
  },
  {
    word: "着る",
    reading: "きる",
    meaning: "입다",
    group: 2,
    forms: {
      masu: "きます",
      i: "き",
      te: "きて",
      neg: "きない",
      past: "きた",
      prog: "きている",
      cond_ba: "きれば",
      cond_tara: "きたら",
      cond_to: "きると",
      cond_nara: "きるなら",
      wish: "きたい",
      vol: "きよう",
      imp: "きろ",
      prohib: "きるな",
      appear: "きそうだ",
      pot: "きられる",
      pass: "きられる",
      caus: "きさせる",
      must: "きなければならない",
      neg_zu: "きずに",
      prep: "きておく",
      try: "きてみる",
      excess: "きすぎる",
      past_neg: "きなかった",
      caus_pass: "きさせられる",
      caus_wish: "きさせたい",
      prog_neg: "きていない",
      prog_past: "きていた",
      pot_neg: "きられない",
      cond_neg: "きなければ",
      wish_past: "きたかった"
    }
  },
  {
    word: "考える",
    reading: "かんがえる",
    meaning: "생각하다",
    group: 2,
    forms: {
      masu: "かんがえます",
      i: "かんがえ",
      te: "かんがえて",
      neg: "かんがえない",
      past: "かんがえた",
      prog: "かんがえている",
      cond_ba: "かんがえれば",
      cond_tara: "かんがえたら",
      cond_to: "かんがえると",
      cond_nara: "かんがえるなら",
      wish: "かんがえたい",
      vol: "かんがえよう",
      imp: "かんがえろ",
      prohib: "かんがえるな",
      appear: "かんがえそうだ",
      pot: "かんがえられる",
      pass: "かんがえられる",
      caus: "かんがえさせる",
      must: "かんがえなければならない",
      neg_zu: "かんがえずに",
      prep: "かんがえておく",
      try: "かんがえてみる",
      excess: "かんがえすぎる",
      past_neg: "かんがえなかった",
      caus_pass: "かんがえさせられる",
      caus_wish: "かんがえさせたい",
      prog_neg: "かんがえていない",
      prog_past: "かんがえていた",
      pot_neg: "かんがえられない",
      cond_neg: "かんがえなければ",
      wish_past: "かんがえたかった"
    }
  },
  {
    word: "覚える",
    reading: "おぼえる",
    meaning: "기억하다",
    group: 2,
    forms: {
      masu: "おぼえます",
      i: "おぼえ",
      te: "おぼえて",
      neg: "おぼえない",
      past: "おぼえた",
      prog: "おぼえている",
      cond_ba: "おぼえれば",
      cond_tara: "おぼえたら",
      cond_to: "おぼえると",
      cond_nara: "おぼえるなら",
      wish: "おぼえたい",
      vol: "おぼえよう",
      imp: "おぼえろ",
      prohib: "おぼえるな",
      appear: "おぼえそうだ",
      pot: "おぼえられる",
      pass: "おぼえられる",
      caus: "おぼえさせる",
      must: "おぼえなければならない",
      neg_zu: "おぼえずに",
      prep: "おぼえておく",
      try: "おぼえてみる",
      excess: "おぼえすぎる",
      past_neg: "おぼえなかった",
      caus_pass: "おぼえさせられる",
      caus_wish: "おぼえさせたい",
      prog_neg: "おぼえていない",
      prog_past: "おぼえていた",
      pot_neg: "おぼえられない",
      cond_neg: "おぼえなければ",
      wish_past: "おぼえたかった"
    }
  },
  {
    word: "止める",
    reading: "とめる",
    meaning: "멈추다",
    group: 2,
    forms: {
      masu: "とめます",
      i: "とめ",
      te: "とめて",
      neg: "とめない",
      past: "とめた",
      prog: "とめている",
      cond_ba: "とめれば",
      cond_tara: "とめたら",
      cond_to: "とめると",
      cond_nara: "とめるなら",
      wish: "とめたい",
      vol: "とめよう",
      imp: "とめろ",
      prohib: "とめるな",
      appear: "とめそうだ",
      pot: "とめられる",
      pass: "とめられる",
      caus: "とめさせる",
      must: "とめなければならない",
      neg_zu: "とめずに",
      prep: "とめておく",
      try: "とめてみる",
      excess: "とめすぎる",
      past_neg: "とめなかった",
      caus_pass: "とめさせられる",
      caus_wish: "とめさせたい",
      prog_neg: "とめていない",
      prog_past: "とめていた",
      pot_neg: "とめられない",
      cond_neg: "とめなければ",
      wish_past: "とめたかった"
    }
  },
  {
    word: "閉める",
    reading: "しめる",
    meaning: "닫다",
    group: 2,
    forms: {
      masu: "しめます",
      i: "しめ",
      te: "しめて",
      neg: "しめない",
      past: "しめた",
      prog: "しめている",
      cond_ba: "しめれば",
      cond_tara: "しめたら",
      cond_to: "しめると",
      cond_nara: "しめるなら",
      wish: "しめたい",
      vol: "しめよう",
      imp: "しめろ",
      prohib: "しめるな",
      appear: "しめそうだ",
      pot: "しめられる",
      pass: "しめられる",
      caus: "しめさせる",
      must: "しめなければならない",
      neg_zu: "しめずに",
      prep: "しめておく",
      try: "しめてみる",
      excess: "しめすぎる",
      past_neg: "しめなかった",
      caus_pass: "しめさせられる",
      caus_wish: "しめさせたい",
      prog_neg: "しめていない",
      prog_past: "しめていた",
      pot_neg: "しめられない",
      cond_neg: "しめなければ",
      wish_past: "しめたかった"
    }
  },
  {
    word: "投げる",
    reading: "なげる",
    meaning: "던지다",
    group: 2,
    forms: {
      masu: "なげます",
      i: "なげ",
      te: "なげて",
      neg: "なげない",
      past: "なげた",
      prog: "なげている",
      cond_ba: "なげれば",
      cond_tara: "なげたら",
      cond_to: "なげると",
      cond_nara: "なげるなら",
      wish: "なげたい",
      vol: "なげよう",
      imp: "なげろ",
      prohib: "なげるな",
      appear: "なげそうだ",
      pot: "なげられる",
      pass: "なげられる",
      caus: "なげさせる",
      must: "なげなければならない",
      neg_zu: "なげずに",
      prep: "なげておく",
      try: "なげてみる",
      excess: "なげすぎる",
      past_neg: "なげなかった",
      caus_pass: "なげさせられる",
      caus_wish: "なげさせたい",
      prog_neg: "なげていない",
      prog_past: "なげていた",
      pot_neg: "なげられない",
      cond_neg: "なげなければ",
      wish_past: "なげたかった"
    }
  },
  {
    word: "答える",
    reading: "こたえる",
    meaning: "대답하다",
    group: 2,
    forms: {
      masu: "こたえます",
      i: "こたえ",
      te: "こたえて",
      neg: "こたえない",
      past: "こたえた",
      prog: "こたえている",
      cond_ba: "こたえれば",
      cond_tara: "こたえたら",
      cond_to: "こたえると",
      cond_nara: "こたえるなら",
      wish: "こたえたい",
      vol: "こたえよう",
      imp: "こたえろ",
      prohib: "こたえるな",
      appear: "こたえそうだ",
      pot: "こたえられる",
      pass: "こたえられる",
      caus: "こたえさせる",
      must: "こたえなければならない",
      neg_zu: "こたえずに",
      prep: "こたえておく",
      try: "こたえてみる",
      excess: "こたえすぎる",
      past_neg: "こたえなかった",
      caus_pass: "こたえさせられる",
      caus_wish: "こたえさせたい",
      prog_neg: "こたえていない",
      prog_past: "こたえていた",
      pot_neg: "こたえられない",
      cond_neg: "こたえなければ",
      wish_past: "こたえたかった"
    }
  },
  {
    word: "する",
    reading: "する",
    meaning: "하다",
    group: 3,
    forms: {
      masu: "します",
      i: "し",
      te: "して",
      neg: "しない",
      past: "した",
      prog: "している",
      cond_ba: "すれば",
      cond_tara: "したら",
      cond_to: "すると",
      cond_nara: "するなら",
      wish: "したい",
      vol: "しよう",
      imp: "しろ",
      prohib: "するな",
      appear: "しそうだ",
      pot: "できる",
      pass: "される",
      caus: "させる",
      must: "しなければならない",
      neg_zu: "せずに",
      prep: "しておく",
      try: "してみる",
      excess: "しすぎる",
      past_neg: "しなかった",
      caus_pass: "させられる",
      caus_wish: "させたい",
      prog_neg: "していない",
      prog_past: "していた",
      pot_neg: "できない",
      cond_neg: "しなければ",
      wish_past: "したかった"
    }
  },
    {
    word: "来る",
    reading: "くる",
    meaning: "오다",
    group: 3,
    forms: {
      masu: "きます",
      i: "き",
      te: "きて",
      neg: "こない",
      past: "きた",
      prog: "きている",
      cond_ba: "くれば",
      cond_tara: "きたら",
      cond_to: "くると",
      cond_nara: "くるなら",
      wish: "きたい",
      vol: "こよう",
      imp: "こい",
      prohib: "くるな",
      appear: "きそうだ",
      pot: "こられる",
      pass: "こられる",
      caus: "こさせる",
      must: "こなければならない",
      neg_zu: "こずに",
      prep: "きておく",
      try: "きてみる",
      excess: "きすぎる",
      past_neg: "こなかった",
      caus_pass: "こさせられる",
      caus_wish: "こさせたい",
      prog_neg: "きていない",
      prog_past: "きていた",
      pot_neg: "こられない",
      cond_neg: "こなければ",
      wish_past: "きたかった"
    }
  }
]